### ISSUE TITLE
Gradle can't resolve

### ISSUE THREAD

**Issue by slm** [channguyen/range-slider-view#1]
Error:(65, 13) Failed to resolve: com.github.channguyen.rsv:rsv:1.0.0
I tried add mavenCentral() but can't success. I will use as library project. Can you fix it :)

**Comment by roxrook** [comment]
My bad, it should be `compile 'com.github.channguyen:rsv:1.0.0'`. Let me know if it works out :+1:

**Comment by slm** [comment]
It works. Thank you
